[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.9"
ethers-core = "2"
futures = "0.3"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-stable-structures = "0.6.0"
serde = "1"
k256 = "0.13"
hex = "0.4"
getrandom = { version = "0.2", features = ["custom"] }
ic-metrics-encoder = "1.1.0"
serde_bytes = "0.11"
